#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi
echo "Dotfiles Installation"

stow -D X11 -t /etc/X11/xorg.conf.d
stow X11 -t /etc/X11/xorg.conf.d

chown root:root /etc/doas.conf

stow -D doas -t /etc/
stow doas -t /etc/
